spring:
  application:
    name: ddns
  profiles:
    active: dev

aliyun:
  ddns:
    fixedDelay: 180
    regionId: cn-beijing
    accessKeyId: LTAI5tAVU2Uf3JhUuUVSd4cH
    secret: tO3FCwfWpWthTAkcUqz2gwb3elxLhe
    domains: cloud.yxb.cool,blog.yxb.cool